"use client";

import { Lexend } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { ThemeProvider } from "@mui/material/styles";
import { SnackbarProvider } from "notistack";
import { theme } from "@/core/theme/theme";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">

      <body className={lexend.variable}>
        <Suspense fallback={<></>}>
          {/* <MyContextProvider> */}
            <SnackbarProvider maxSnack={3} preventDuplicate anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}>
              <ThemeProvider theme={theme}>
                {children}
              </ThemeProvider>
            </SnackbarProvider>
          {/* </MyContextProvider> */}
        </Suspense>

      </body>
    </html>
  );
}
